### ISSUE TITLE
Convert references to nx-staging to use "production" server.

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/nexus-repository-installer#9]
Update docs to change references to `nx-staging` to point to new "production" server. 

This basically means replacing:
`https://nx-staging.sonatype.com...`

with:
`https://repo.sonatype.com...`

Next step will be to remove deployment to `nx-staging` before that server goes away.

**Comment by jeviolle** [comment]
Is there a need for a "staging" repository on repo.sonatype.com? Essentially there is an nx-staging and nx-prod, but effectively nx-staging is going away and nx-prod is being replaced.
